<?php

namespace foo\FooBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FooRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FooRepository extends EntityRepository
{
}
